name: Run GitHub Actions tests

on:
  push:
    branches: [ main, development, experimental ]
  pull_request:
    branches: [ main, development, experimental ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.12", "3.13", "3.14" ]
        runs-on: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install requirements
      shell: bash
      run: |
        
        if [[  ${{ matrix.python-version }} == "3.13" ]] || [[  ${{ matrix.python-version }} == "3.14" ]]; then 
          pip install -r requirements_py3.13.txt
        else
          pip install -r requirements.txt
        fi

    - name: Test some Python scripts
      run: |
        echo "Running tests..."
        cd python 
        python LoadCSVData.py -nogui 
        python LoadMatData.py -nogui 

    - name: Test running the notebook
      run: |
        pip install nbmake  
        cd notebooks  
        pytest --nbmake GurnaniData.ipynb 

    - name: Test creating NWB file
      run: |
        cd python 
        python CreateNWB.py

    - name: Final information on installed packages
      run: |
        echo "Installed packages:"
        pip list
